name: autopublish (dry-run safe)

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "docs/**"
      - "config/**"
      - "requirements.txt"
      - ".github/workflows/autopublish.yml"
#  schedule:
#    - cron: "17 14 * * 5"  # uncomment in Step 5 (Fridays 14:17 UTC)

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          python -c "import sys; print(sys.version)"

      - name: Install Playwright browser (even if dry-run)
        run: |
          python -m playwright install chromium --with-deps

      - name: Run pipeline
        env:
          BRAND_NAME: ${{ secrets.BRAND_NAME }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
          DEFAULT_PRICE_USD: ${{ secrets.DEFAULT_PRICE_USD }}
          PAYHIP_EMAIL: ${{ secrets.PAYHIP_EMAIL }}
          PAYHIP_PASSWORD: ${{ secrets.PAYHIP_PASSWORD }}
          BUTTONDOWN_API_KEY: ${{ secrets.BUTTONDOWN_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python src/pipeline.py

      - name: Commit & push catalog + artifacts
        run: |
          git config user.email "bot@github-actions"
          git config user.name "github-actions"
          git add docs/products.json data/products || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "autopublish: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
