name: sanity
on:
  push:
  workflow_dispatch:
jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Repo wired. Next steps will add the automation pipeline."
