name: autopublish (dry-run safe)

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "docs/**"
      - "config/**"
      - "requirements.txt"
      - ".github/workflows/autopublish.yml"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          python -c "import sys, pkgutil; print(sys.version); print('yaml installed:', bool(pkgutil.find_loader('yaml')))"

      - name: Sanity: show tree
        run: |
          ls -R

      - name: Run pipeline (dry-run)
        env:
          BRAND_NAME: ${{ secrets.BRAND_NAME }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
          DEFAULT_PRICE_USD: ${{ secrets.DEFAULT_PRICE_USD }}
          PAYHIP_EMAIL: ${{ secrets.PAYHIP_EMAIL }}         # placeholder → dry-run
          PAYHIP_PASSWORD: ${{ secrets.PAYHIP_PASSWORD }}   # placeholder → dry-run
          BUTTONDOWN_API_KEY: ${{ secrets.BUTTONDOWN_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          set -e
          python src/pipeline.py

      - name: Commit & push catalog + artifacts
        run: |
          git config user.email "bot@github-actions"
          git config user.name "github-actions"
          git add docs/products.json data/products || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "autopublish: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
